### ISSUE TITLE
Can't Reproduce results for crafts dataset

### ISSUE THREAD

**Issue by AfrinaVT** [EagleW/Multimedia-Generative-Script-Learning-for-Task-Planning#1]
Hi, 
Thank you for making the code public. I ran the code multiple times and couldn't reproduce the results in the paper. Here are the reproduced results using the repository. Can you tell me the reason behind the difference?
<html><body>

Reported | 21.3 | 11.8 | 7.12 | 4.85 | 20.3
-- | -- | -- | -- | -- | --
Reproduced | 19.50 | 10.53 | 5.89 | 3.73 | 19.37

</body>
</html>

**Comment by EagleW** [comment]
Hi @AfrinaVT Thank you for your interest in our research. I have attached my [craft checkpoint](https://drive.google.com/file/d/13YxtAqHJFjw_9ZVGA0w1ixTGVhfr-L0z/view?usp=sharing) for reference.  It's important to consider that variations in outcomes can arise due to differences in computer configurations. This variability is not uncommon, especially since both weight initialization and contrastive learning inherently involve random processes.

If you have any further questions or need more clarification, please don't hesitate to reach out.

**Comment by AfrinaVT** [comment]
Thank you very much for sharing the checkpoint for craft. Is it possible to share the checkpoint for gardening as well?

**Comment by EagleW** [comment]
Sure, the gardening checkpoint is [here](https://drive.google.com/file/d/1PpOfHtsZWS2V05RqMOu-EOOTR8dLbzFR/view?usp=sharing)

**Comment by AfrinaVT** [comment]
Thank you very much!
